### ISSUE TITLE
Host Address Disconnected Cant Solve

### ISSUE THREAD

**Issue by benc6190** [nefarius/ScpToolkit#1016]
I can not seem to get my ps3 controller to work, Ive used it in past years using the Bruce James SCP Tool but I reset my computer a year ago or so and wanted to use it again now. I downloaded the new SCPToolKit and could not get it to work so I tried the older one and still did not work. Both have this same problem where it says Host Address Disconnected. I connect my ps3 controller to my pc using a USB and it seems it recognizes my controller but host address is disconnected.  Also, in Device Manager it still says PS3 controller, not XBOX. Please help!
also im using windows 8.1

![host address disconnected](https://user-images.githubusercontent.com/34901737/34397645-cb4c399e-eb45-11e7-814a-22d1decf2d5e.png)

**Comment by ocxty** [comment]
When you run ScpDriver.exe and the install window pops up, be sure to check off "Configure Service" AND "Bluetooth Driver". Because you're on Windows 8.1, I don't think you have to check off the "Force Install". If it doesn't work the way I suggested first try checking off all three boxes and then installing.
