### ISSUE TITLE
Sony DualShock 4 Found but not connecting

### ISSUE THREAD

**Issue by n3krO** [nefarius/ScpToolkit#180]
So, I installed ScpToolkit and after that I installed the Bluetooth driver using ScpDriverInstaller to replace the original driver.

I had my controller connected to the dongle when I did that and it disconnected and I can no longer pair the controller to the dongle using Windows 10 pairing screen.

Now when I press the playstation button in my controller it starts flashing and then the ScpToolkit Information tab opens saying "Sony DualShock 4 Found" and the controller turns off.

When I was using the USB cable I was using the DS4 to Xinput but it freezes my bluetooth connection (I can use the controller as a normal controller but can't trick windows to think it's a xbox controller)

The USB Dongle I'm using is officially supported (Asus BT400)

**Comment by n3krO** [comment]
Here's the log from ScpServer:

![captura de tela 2016-01-24 16 47 04](https://cloud.githubusercontent.com/assets/8856598/12537242/532c64e4-c2ba-11e5-8d5e-c0a19364ac62.png)

**Comment by WhiteZeroX** [comment]
I have basically the same issue. I can pair my three DS3 controllers just fine, see them in SCP Monitor normally and use them as XInput controllers. I can plug my DS4 into USB, it shows up and works as XInput as well. But when I try to use the DS4 over Bluetooth, I get the "Sony DualShock 4 found" but it dosen't work at all otherwise. Here's my logs and similar screenshot to OP's. 

[ScpToolkit_Log-Package_Nick_1453654623.zip](https://github.com/nefarius/ScpToolkit/files/102437/ScpToolkit_Log-Package_Nick_1453654623.zip)

**Comment by n3krO** [comment]
It seems the bluetooth dongle was broken, already sent to replace.
