### ISSUE TITLE
The driver for the virtual xbox 360 controller is not detected as a game controller (version 1.7)

### ISSUE THREAD

**Issue by DorCoMaNdO** [nefarius/ScpToolkit#264]
I updated to the new 1.7 update, then my controller wouldn't work. I tried to reinstall and it didn't work, I uninstalled the DS3 driver (as it was the one from the new updated, hoping it would use the older driver), didn't work, I tried to install an older version and it didn't work, I then saw that the driver for the virtual controller was updated too, I uninstalled that driver, reinstalled the older version yet again and then the controller was detected yet again.
The new virtual xbox 360 controller does appear, but it's not in the list of game controllers and does not receive/send any input.

**Comment by charlesmilette** [comment]
Have you noticed that a clean wipe is needed?

**Comment by DorCoMaNdO** [comment]
I did, and I performed it... The clean wipe does not seem to remove the older drivers once they're installed in the system.

**Comment by charlesmilette** [comment]
Try to remove any Xbox 360 virtual controllers, PS3 controllers and the Virtual Bus from the Devices Manager and the Driver Store. Then retry installation of the drivers

**Comment by DorCoMaNdO** [comment]
I've done that, uninstalling the driver was the only way to fix it. I've reinstalled the driver a bunch of times already and that did not help, the issue remains the same, the controller appears as a detected device in the devices manager, it recognizes it as an xbox 360 controller, but it won't work in games, won't send or receive any input, checking the "Game Controllers" setting doesn't show the controller there, while the older drivers do.

**Comment by Neurotic0416** [comment]
Same problem here. Controller is connecting and got this error:
![2016-04-11_22-52-16](https://cloud.githubusercontent.com/assets/13425090/14442885/68c3efec-003c-11e6-9ec3-fb54c297f2e9.jpg)

I see the connected controller in the scp monitor, but it doesn't working. I tried clean wipe and reinstall drivers but I got same result all the time.

**Comment by nefarius** [comment]
That's because I'm an idiot >_< I somehow overlooked that the wrong hardware ID is in the `Ds3Controller.inf` file. If you have a look in your device manager you should see something like this:

![](http://content.screencast.com/users/Nefarius/folders/Snagit/media/e55ff274-af1b-4745-8155-4a7669180300/04.12.2016-18.02.png)

For a manual fix, try replacing the assigned drivers manually:

![image](https://cloud.githubusercontent.com/assets/286631/14467390/67e5fabc-00db-11e6-83d2-a716a9a89422.png)

![image](https://cloud.githubusercontent.com/assets/286631/14467403/80867790-00db-11e6-8fbb-d01dcde075f2.png)

![image](https://cloud.githubusercontent.com/assets/286631/14467423/8dc45544-00db-11e6-8510-c13122bc5c2a.png)

![image](https://cloud.githubusercontent.com/assets/286631/14467425/90fa7054-00db-11e6-91c6-0830e838052e.png)

![image](https://cloud.githubusercontent.com/assets/286631/14467432/94455b2a-00db-11e6-89d7-6a9826b92b5a.png)

**Comment by Neurotic0416** [comment]
Thx. But when I installed the driver manually I got blue screen with "DRIVER_VERIFIER_IOMANAGER_VIOLATION (ScpVBus.sys)" message. I got this messege in 1.6 version of ScpToolkit before. Thats why I wan't to install 1.7

**Comment by lilyesx6** [comment]
Thanks Nefarius it's really a an excellent software, I hope you ad a support feature for fake ps3 controllers. Keep the good work <3

**Comment by Neurotic0416** [comment]
I used the Driver Verifier Manager, deleted existing settings and now I have not DRIVER_VERIFIER_IOMANAGER_VIOLATION error and the controller works fine.

**Comment by nefarius** [comment]
I ran the latest `ScpVBus.sys` with the verifier enabled and didn't get an DRIVER_VERIFIER_IOMANAGER_VIOLATION error any more. Can you try again but first check which version of the bus driver you are running?
