### ISSUE TITLE
Dual Shock 3 Input goes berserk

### ISSUE THREAD

**Issue by lucaslizama** [nefarius/ScpToolkit#276]
Using an original DS3 either via bluetooth or cable has certain inputs being constantly called.
For example R1 is always bieng pressed, "Square" is intermitent, and other buttons like X also present this behaviour.
I'm on Windows 10 pro original, everything update, also my controller is not defective, works fine with my Playstation 3.

Tried with the stable release, with the beta release and with an older 1.5.7 release, same problem, just diferent buttons going crazy.

**Comment by acme420** [comment]
how far away from the machine are you? when i use my controllers on bluetooth i have to make sure there isn't too much stuff between me and the radio. bluetooth has a really short effective range. even just crossing my legs and holding my controller in my lap blocks the signal so much that i have input lag like you're talking about where keypresses either stick of are delayed or don't register at all till i uncross my leg so that there's a clearer line of sight from my controller to my computer.
