### ISSUE TITLE
Analog stick randomly moving to the upper left

### ISSUE THREAD

**Issue by dankimxdd** [nefarius/ScpToolkit#315]
So every so often there will be an input to move towards to upper left. I don't know why its happening but I keep crashing jets because of it.
[ScpToolkit_Log-Package_Daniel_1464048160.zip](https://github.com/nefarius/ScpToolkit/files/278500/ScpToolkit_Log-Package_Daniel_1464048160.zip)
Updated to the 1.7 beta (latest) problem is still there. Left analog stick randomly moves.
[ScpToolkit_Log-Package_Daniel_1464081738.zip](https://github.com/nefarius/ScpToolkit/files/279152/ScpToolkit_Log-Package_Daniel_1464081738.zip)

**Comment by threydor** [comment]
Have you tried setting dead-zone treshold to higher value? It looks like a hardware problem to me (my analog stick is worn out and i had the same problem).

**Comment by Diagonet** [comment]
So, made an account just for this issue. I had the same problem with my ps3 controller and no amount of dead-zone would make it better. I tried to use a brand new ps3 controller and the issue was gone.

Still, using the "faulty" controller with my ps3 does NOT cause any issues, which makes me think that maybe, while having a hardware side to this problem, it could also be fixed with ScpToolkit on the software side.
