### ISSUE TITLE
Updated version doesn't work with Built-in Bluetooth

### ISSUE THREAD

**Issue by YNagato** [nefarius/ScpToolkit#435]
The old version 1.6.238.16010 of ScpToolkit worked perfectly with my built-in Bluetooth. But after I updated to Ver. 1.7.277.16103, and even though the re-installation of the driver looked all successful, the built-in Bluetooth no longer works with my DualShock3. (In contrast, my extra USB dongle work well with both versions.)

My built-in Bluetooth is Intel Bluetooth (HCI version: 6.7869, LMP version 6.64512).

Would you give me some help? Thanks!

**Comment by rafsanjani** [comment]
Did you try using the force install option?

**Comment by rafsanjani** [comment]
in the ScpConfig.ini file, find the hardward ID of your built-in bluetooth device and append to the end of the list.
this is usually the last line
`HardwareId = USB\VID_04CA&PID_300B`
append your custom hardware id so that the list becomes something like this

`HardwareId = USB\VID_04CA&PID_300B`
`HardwareId =[your bluetooth device hardware ID]`

after that, run the scpdriverinstaller again and it should detect your built in bluetooth
