### ISSUE TITLE
BSODs on W7 Pro

### ISSUE THREAD

**Issue by RogueLizard** [nefarius/ScpToolkit#671]
Getting SYSTEM_SERVICE_EXCEPTION with Bluetooth plugged in during startup. Uninstalled SCP driver, problem went away.

System specs:
AsRock H77M
i5 3330 at 3.8GHz
8GB Corsair XMS3
nVidia GTX 1050ti SC
nVidia GTX 460
600W Corsair CX600

Updated to the newest version just now, instant BSOD on controller connection through BT.

Holy shit Nefarious, are you doing this on purpose? Literally the only thing this program has done is cause issues, crashes, BSODs, driver corruption...and hasn't been updated since April of 2016.

Cunt.

Latest crash playing Fallout 4 on 3 screens (4280x1024)

**Comment by rougetimelord** [comment]
lol, write your own tool if you want to be so disrespectful 😄

**Comment by charlesmilette** [comment]
Works on my machine™

**Comment by RogueLizard** [comment]
I'm gonna stick with my PS3 controller for now with Better DS3 and
MotionInJoy, something that I have NEVER had any issues with...take hint
Nefarious...

DriverVerifier hates the virtual bus driver, by the way. You should fix
that...lots of issues with it that produce blue screens.

**Comment by deadair3210** [comment]
MotionJoy has been shown multiple times to cause more harm than good.
ScpToolkit works fine on my machine, as well as many many others, the fact that you seem to think that the dev needs to immediately jump to action just because it doesnt work on your machine makes my head hurt.

People like you insulting devs just because you can't do anything else productive with your time is why most projects end up dying. Either help find and fix the problem if you can, or put a issue report in and wait like everyone else. You have no right to try to rush someone without any intention of helping

**Comment by charlesmilette** [comment]
In my case, MotionInJoy was a pile of trash that never worked. While with ScpToolkit it's literally plug and play.

It really depends on the hardware setup.
