### ISSUE TITLE
Controller only working with "SCP Server" panel open

### ISSUE THREAD

**Issue by canastra** [nefarius/ScpToolkit#678]
i'm having some issues with the scp
my pc only recognize my controller if this panel is open
![image](https://cloud.githubusercontent.com/assets/26560693/24130484/8a28013e-0dc7-11e7-9654-59b1a74f7415.png)

i know i can use the controller anyway but, its kinda annoying to have to open this panel every time i want to use it
i already have tried lots of solutions
uninstalled the scp and the xbox driver
install as adm
but nothing work

please, if someone can help me

thanks! 

(sorry for the possible typo or bad english)

**Comment by jacobmix** [comment]
I sometimes have to start the service because it doesn't on startup. Try this:
Make a bat file (name it whatever) in a folder you'll remember (i have a folder for all my ScpToolKit stuff)
![SCPimage1](http://image.prntscr.com/image/df3aec32cbf345289298b0111239b8b3.png)
Write this in the bat file: 
net start "SCP DSx Service"
![SCPimage2](http://image.prntscr.com/image/046eb452c77146b4a8a7e1d99bc5de71.png)
Save it. It needs to be run as admin to start it tho.
You can make shortcut that will run it as admin.
Then go to the "Shortcut" tab, and click "Advanced..." Should be a "Run as administartor" checkbox.
![SCPimage3]([http://image.prntscr.com/image/7c02f99150744180bc783d8596d4cc44.png)
You can also check the service to see if it's set to start up automatically or not in services.msc
You can just search/run "services" or go through "Task Manager>Services tab>(Admin)Services..." to open it.
