### ISSUE TITLE
ScpToolkit Driver Installer stuck

### ISSUE THREAD

**Issue by therealdio** [nefarius/ScpToolkit#682]
![image](https://cloud.githubusercontent.com/assets/20807357/24402543/b8d4fa6e-13c1-11e7-90bf-09a84ffc02cc.png)
It's been stuck like that for the past 30 minutes. What do i do?

**Comment by therealdio** [comment]
![image](https://cloud.githubusercontent.com/assets/20807357/24403503/dbe0172e-13c5-11e7-8bb0-e7418ca1c4f4.png)
I also get this when I connect my ds3.

**Comment by Kazekai** [comment]
I have the exact same problem all the time, especially when I need to reinstall the damned thing because for SOME REASON, it constantly uninstalls itself or won't work at all when I plug in my controller. Restarting the PC is the only solution I know of. You can also try killing the service but that usually results in the service not being able to start again and requires a reboot anyway.

**Comment by HyeVltg3** [comment]
Fixed this issue by Disabling Driver Signature requirement
Google how its done for W10
On W7, press F8 at boot (beep)
choose last option "Disable Driver Signature" (worded differently)
now SCPtool Driver Installer should finish.
Working perfectly for me now.
leaving this here as this page was one of my google hits.
