### ISSUE TITLE
(Windows 10 Creators Update 1703, Dualshock 3) Tray Notification Crashes and Driver Installer does not work

### ISSUE THREAD

**Issue by DoctorCandor** [nefarius/ScpToolkit#726]
Upgraded my desktop to 1703 - my Dualshock 3 is no longer detected, trying to restart the Tray Notification crashes it, nothing appears after running the driver installer. Reinstalling changes nothing. Rolled back to 1607 and works just fine after a repair installation - I'll stay there until there's a way to work around it.

Strangely, my laptop running Windows 10 Education has no issues with SCP Toolkit on 1703. Can't figure out the difference yet.

**Comment by novedevo** [comment]
From what I can tell, it is because SCPToolkit uses .NET.  Microsoft updated to .NET 4.7 in the creators update and this broke compatibility with SCPToolkit.  Attached are two snips from Windows Event Viewer, caused by the tray application crashing when it tried to do anything.
![capture](https://cloud.githubusercontent.com/assets/20878868/25160658/31ad6c7c-246c-11e7-83b8-84a8de99b246.PNG)
![capture1](https://cloud.githubusercontent.com/assets/20878868/25160657/31ad1358-246c-11e7-8362-299a92fa1378.PNG)

**Comment by DoctorCandor** [comment]
Huh. Hope that's the only incompatibility going on here.

**Comment by novedevo** [comment]
There also might be something going on with directX.  One of the errors there mentioned d3d9.dll.  I reinstalled dx9, but no change.

**Comment by DoctorCandor** [comment]
I see. I did try the more recently updated solution with FireShock + ViGEm on 1703, but couldn't get it to work and the documentation wasn't very clear on how to properly install everything. I managed to blue screen after trying to reinstall drivers included with ViGEm and just decided to roll back to kill two birds with one stone. Best I can do for now is to wait. Heard around on the web that 1703 is causing more problems than 1607 did.
