### ISSUE TITLE
Service not working correctly

### ISSUE THREAD

**Issue by marysiamzawka** [nefarius/ScpToolkit#765]
Windows 7 x64 here.

I've been using the original SCP before and everything worked fine.
Got my hands on this version, so did a clean wipe and everything. 
My pad is detected by the program, by something had gone wrong in the process apparently.
Looks like the SCP service failed to install, even though I did restart after installing, then reinstalled it a few times again, and even went as far as to do another clean wipe.
![obraz](https://cloud.githubusercontent.com/assets/20336327/26306071/449514ac-3ef2-11e7-8dc9-cdf1e17bbfb2.png)

The controller itself is not being picked up by either Game Controllers applet or Xbox 360 Accesories thing.

**Comment by jacobmix** [comment]
Not sure if it's the same problem i've been having. But SCP Service doesn't start (Or crashed?)sometimes  for me.
I have a [shortcut](https://docs.google.com/document/d/116LwfIM6evk4Dy89N1EQjGYVbcgdIX3cHE8CIR1pflk/edit?usp=sharing) for starting the service tho, and works fine after i run it.

**Comment by marysiamzawka** [comment]
> I have a shortcut for starting the service tho, and works fine after i run it.

Tried it, but the service just refuses to start.

Also tried to start it through Services applet, with same results.

![obraz](https://cloud.githubusercontent.com/assets/20336327/26357677/5afb0f56-3fd0-11e7-926a-d132bbfd93c2.png)

(it says "Starting dependance service or group failed")

**Comment by jacobmix** [comment]
Try going into services.msc to see if your SCP Service is called "SCP DSx Service" Might be different.
Also updated some info on the shortcut about this. You could also try "sc start" instead of "net start"
https://superuser.com/questions/315166/net-start-service-and-sc-start-what-is-the-difference
Not that i think it'd do anything. Try looking in services.msc or uninstall, reinstall everything again.
Hope you get it working. Sorry for late reply.
