### ISSUE TITLE
"Fake" Controller works with cable, shows as connected via BT, yet it's not

### ISSUE THREAD

**Issue by starg09** [nefarius/ScpToolkit#90]
All right, so apparently I just purchased a fake DS3. I'm totally fine with it, as it works on the PC as I intended. Well, at least on cable.

I get a "Fake controller" warning on connection, but it works perfectly. When I try to connect it through Bluetooth, though, I get a "Fake controller, trying workaround 1" warning, a "Connected on virtual port 1" message, yet it doesn't seem to work (neither does the controller mark it being connected as joystick 1.

Not sure what specific fake model it is, all I know is that it originally said "PS(R) Controller" as the device, and didn't work at all before using SCP. I have Windows 10 Pro T2, 64-bit.

I attach the debug info, and the notifications I get when connecting via bluetooth (that is, pressing the PS button with the dongle connected and configured)

![7mhffss](https://cloud.githubusercontent.com/assets/1235066/11821729/c479d6f8-a349-11e5-9ee6-fceeb7174bb1.png)

[The debug info](https://mega.nz/#!M5EHUYIT!ZbhkEkTZXpSsV0qvYeY9YAjA0658xweFxrSVgVYcd6U) (GitHub won't let me upload the zip for some reason)

**Comment by nefarius** [comment]
Your service log is damaged and can't be read. Please repeat the connection procedure and shut down the service before you run the debug collector!

**Comment by starg09** [comment]
Ok, one second.

**Comment by starg09** [comment]
https://mega.nz/#!UlsxwBYT!_9rFgCwTgtZFOquRduxoj7QLAg2_JjI2m9L_xHa4kJM

**Comment by nefarius** [comment]
The error is still there, please stop the service, go to your installation directory, delete the file `Logs\ScpDsxService_GUILLE7$.log.xml` and repeat the steps above.

**Comment by starg09** [comment]
All right. Maybe it's because I'm on a limited account (with access to admin, but still)

**Comment by starg09** [comment]
https://mega.nz/#!E1lzxSLI!7s-4Xnvdd0sb7zdq8R0WEIe6rv3aKkvtuO5fcUJIuUk

**Comment by nefarius** [comment]
It is! But could you also make a screenshot of ScpToolkit Monitor while it's supposedly connected via Bluetooth?

**Comment by starg09** [comment]
Connected via cable: http://i.imgur.com/L9WmxRu.png

Once disconnected: http://i.imgur.com/fGC0Bvu.png

Once "Connected": http://i.imgur.com/6HKPs11.png

**Comment by starg09** [comment]
On a side note: I forgot to check that before, but I had read something about that "0000 None" error. Although it might not be even important, I tried stopping the service, opening it through the standalone version, and once in that state checked if the "Vibration" buttons worked. They don't.

**Comment by nefarius** [comment]
Mystery solved; these zeros are the packet counter; if it stays at zero that means the data the controller is sending can't be interpreted. For the moment you're simply out of luck, sorry.

**Comment by starg09** [comment]
Oh, okay. Thanks for checking anyway...

At least it works with cable, it's something :P

**Comment by nefarius** [comment]
I will come back to the counterfeit ones but just no time at all right now =/

**Comment by starg09** [comment]
Sounds great to me. No hurries, thanks for working on this! :D

**Comment by angelflames1337** [comment]
I am having the exact same issues. Not to push you or anything, but will the fake support come within these 2 months? Coz if it is, I am preordering a game tomorrow to use this :p

**Comment by Koeleskab** [comment]
I have the exact same issue on USB with what turns out to be a counterfeit DS4 controller. Should i send along the logs, in case the time ever comes for the lesser issues?

**Comment by xorincret** [comment]
@nefarius 

Same issue here, fake DS3.

Pairing should be OK since the PC and controller can communicate enough to determine it's a 3rd party controller. I would assume that the controller's interpretation of the protocol is also fairly compliant given that it's marketed for use with the original PS3.

Any logs I can provide that would give you a head start on fake controllers, or this one specifically?

I had a look at the logs in the generated zip but they didn't have much useful information IMHO. Perhaps I don't know what to look for. Is there a feature in ScpServer that can be activated to save BT packets to disk? This should be useful for debugging, to have users with fake controllers send their packet dump.

I don't mind putting in a few hours of coding if it would help the project advance.

**Comment by nikhosagala** [comment]
I've some issue here.

**Comment by nefarius** [comment]
@xorincret: I got some different "breeds" of those PANHAIs donated a few month ago and had them disassembled. I managed to tap into the communication between the Bluetooth controller chip and the micro controller (they communicate via UART thankfully) and actually could sump the streams they exchange when connecting to a genuine Sony PlayStation 3. 

Since my knowledge of the whole Bluetooth specification (if I recall correctly, v4 has nearly a 1000 pages...) is very limited I wasn't yet able to decipher those dumps. I don't have much time either since I'd like to focus on development rather than reverse engineering. 

The Logs the toolkit produces won't help much since the inner workings of the protocols involved aren't logged since it would add too much of an overhead.

What I've discovered so far is, that the **actual** pairing (sadly people misuse this term all the time; the flashing LEDs do not necessarily indicate a pairing problem) works fine, it's the L2CAP connections which fail after responding to a connection and configuration request. The PANHAIs just don't send the 3rd connection request for the HID Service channel which the originals do just fine. That's where the software is currently stuck.

If you want to know more about the inner workings of the Scp Bluetooth stack don't hesitate to ask.

**Comment by luzair** [comment]
@nefarius I have the same issue "Fake controller detected". Should I ask for a refund from the supplier? The supplier told me its a genuine sony controller. I was wondering why old version of motioninjoy and scpserver works with bluetooth, but ur latest version doesnt work with bluetooth on these fake controllers?

When using old scpserver, I can get my controllers to vibrate on usb mode, but not on bluetooth mode. PS. I can connect via bluetooth using old scp server method to this fake controllers.
Please advise.

**Comment by starg09** [comment]
@luzair not nefarius but you should. I did, same situation (sold as
original), mentioned that seemed to not be the case and I was almost
instantly offered "a replacement or a refund". Who knows, maybe those fancy
camouflage ones they sell are actually original, or they offer a dualshock
4 (I can dream hehe :P ) (seriously, I'll most likely get refunded)

So, long story short: you should ask for a refund xD

**Comment by luzair** [comment]
@starg09 Thanks for the advise, I will contact my supplier asap. What about rumble support for old scp version. using SCP-DS-Driver-Package-1.2.2.175. I can get it to work via bluetooth but with no rumble support.

**Comment by aking4125** [comment]
I can confirm the fake controllers working with "SCP-DS-Driver-Package-1.2.2.175" via bluetooth flawlessly. I don't understand they don't work in this new toolkit thing. Both works with USB though.

**Comment by luzair** [comment]
@aking4125 When u use Fake DS3 and SCP-DS-Driver-Package-1.2.2.175 via bluetooth, do u have rumble or vibration while playing games?

**Comment by aking4125** [comment]
@luzair Nope. But I don't really care. So long as it works. Though now out of nowhere, 1 of the controllers is not being detected and it refuses to install the controller drivers. Then I BSOD'd. This is getting crazy.

**Comment by luzair** [comment]
@aking4125 I think ur controller's battery is burnt. 
I remember having rumble via bluetooth when i used motioninjoy. but im not sure if I should use MIJ again. Any suggestions?

**Comment by aking4125** [comment]
The vibration works perfectly fine otherwise. My controllers is fine as they work via USB. 

What I'm trying to say, The SCP-DS-Driver-Package-1.2.2.175 was the only way to get them to work via Bluetooth. This SCP Toolkit, doesn't work with bluetooth. Both works with USBs. So since the other one worked. I used that and everything was fine until I restarted my PC. It didn't restart properly, it BSOD'd with the SCPVBUS error or something. Restart. Now the old software refuses to install the controller drivers. I cannot gain access to my system32 folder to manually copy them anymore. 

Trying the toolkit again and it looks like I have to reinstall Windows.

**Comment by luzair** [comment]
Yes, I really don't wana use MotioninJoy, I will still with SCP-DS-Driver-Package-1.2.2.175 then.

@aking4125 You can try uninstallling relavant softwares one 1 by then restart. Then try clean registry with CCleaner. I know formatting windows is a pain.

I hope somebody can tell me, how to make fake DS3 have rumble via bluetooth.

**Comment by aking4125** [comment]
None of that worked. It can't seem to gain access to the system32 folder. I found a way for me to do it. Now the SCP-DS-Driver-Package-1.2.2.175 doesn't work with USB. BUT! Bluetooth works flawlessly again! Thank god. That's all I wanted was the controllers to function. Vibration doesn't work like this but it's not the enough of the world for me. 

Now, SCP Toolkit, won't work with Bluetooth. Period. I don't understand why though.

**Comment by luzair** [comment]
@aking4125 I don't know what are you doing to ur poor pc haha

The only person who knows why SCP Toolkit won't work with bluetooth is @nefarius.

**Comment by luzair** [comment]
Do you think we should like Better DS3?

**Comment by aking4125** [comment]
I know what I'm doing as I manged to get it to work. Now my family can play Viscera Clean-Up Detail wirelessly with our PS3 controllers

Better DS3 requires the normal DS3 tool drivers, which means you need MotioninJoy. Don't use it. For now, if users want bluetooth on some crap 3rd party PS3 controllers. If SCP ToolKit doesn't work, use the old SCP-DS-Driver-Package-1.2.2.175 for that. Otherwise just use SCP Toolkit. 

I think it'd may be best to just get Xbox 360 controllers or Playstation 4 controllers. Even though they are much more expensive than the cheap PS3 controllers (I got the four I'm using for $9 each). Because with those, especially the PS4 controller. They just work without having a 3rd party Bluetooth driver. And DS4 is easier to use. Too bad that doesn't work with PS3 controllers.

I bid @nefarius luck with whatever the issue is. Cause in SCP-DS-Driver-Package-1.2.2.175 Bluetooth works, just no vibration which I don't mind at all.

**Comment by angelflames1337** [comment]
Aking, unfortunately SCP-DS-Driver-Package-1.2.2.175 doesnt work for me. I click the scpdriver.exe and nothing happened. Check the task manager and it seems the exe appear for a few seconds then it gone. Tried to unblock, zip/unzip and few other thing, nothing works. I just want a bluetooth function on my ps3 controller T_T

**Comment by aking4125** [comment]
@angelflames1337 You installed it incorrectly. You have to load the 1.2.0 files first. then the 1.2.2 files and replace everything. That's because the 1.2.2 is just an update. The core files is within' the 1.2.0 archive.

This doesn't explain however why the Toolkit doesn't work in Bluetooth mode. But the old 1.2.2 one does.

**Comment by angelflames1337** [comment]
Ah I see, I'll try that and get back here :)

**Comment by aking4125** [comment]
This isn't the thread or place to be talking about this. Perhaps another time via a PM or something.

**Comment by nefarius** [comment]
@aking4125 the reason for my fork behaving differently than the original Scp drivers is simple: I **hate** hacks where even if you kind of understand what the code does you still have no idea why it works. I ripped out a good bunch of those mysterious sections (beware that the original code base was poorly documented too) so I could **continue** working in refining and enhancing the software without pissing genuine owners off because the "fake workarounds" can (and did) break connectivity with Sony controllers. So I'm simply playing safe until I was able to fully understand and reverse engineer the counterfeit ones to code a *real* solution that's reliable and stable.

I hope this answer clears things up for you.

**Comment by luzair** [comment]
@nefarius I would like to make a personal request to you. Hope to get a favorable reply. 

Currently I'm using fake controllers with SCP-DS-Driver-Package-1.2.2.175. When using USB, vibrations work, but when using bluetooth vibrations don't work. Please help to get vibrations to work via bluetooth. It will benefit  many, me included, who got deceived by sellers who sold these fake controllers as the authentic ones. I know you can do it and hope you will help us.

**Comment by aking4125** [comment]
@nefarius Yes that makes sense. Well, until you do. Users such as myself cannot use SCP Toolkit for Bluetooth with some PS3 controllers. I tried I genuine Sony PS3 controllers from a friends PS3. That still didn't work via Bluetooth with the Toolkit. The 1.2.2 older drivers does for some reason.

@luzair The old SCP 1.2.2 drivers is not under nefarlus at all. That one is no longer supported. So you are stuck without Vibration via Bluetooth. I honestly don't even think that's an issue. So long as the controllers work then just leave it be. But until nefarlus can figure out the issue with the Bluetooth in the current SCP Toolkit. There is nothing can really be done. As seeing how our issue seems to be very specific. It may never happen. 

I'm just going to save up what little money I have and get 3 more legit PS4 controllers and use DS4. I do want to use my Bluetooth adapter for other stuff and with the PS3 controllers I can't really do that which for now it isn't an issue to me. Or I should just buy another Bluetooth adapter for everything else.

**Comment by luzair** [comment]
@aking4125 The most cost effective option for you is to buy another bluetooth dongle. After going so much hassle with ps3 controllers, next time im buying an xbox360 controller. hope they are legit as they claim to be. sometimes i think those third party gamepads that can emulate x360 profile out of the box are much more hassle free. Happy New Year every1.

**Comment by aking4125** [comment]
Yeah. But I do play PS2 and PS1 games and playing them with an Xbox 360 controller is annoying you know? 

Besides, the Xbox controllers usually require batteries and a rechargeable pack is just extra money. I'll eventually get them all. And I will get another Bluetooth dongle. I'm aware. I'm still gonna get 3 more PS4 controllers though cause this was more hassle than it needed be xD

**Comment by aking4125** [comment]
@angelflames1337 If even the old SCP 1.2.2 doesn't work for you in Bluetooth. Either make sure the Bluetooth Drivers and DS3 drivers are properly installed or you're Bluetooth Dongle is not supported.

If the installation reads it cannot write the files to the system32 folder. You need extra permissions to get that working. You need to select the .exe. Make sure to run it as an Admin. And then, go to the special Permissions and allow your current Admin account Effective access. That's what I had to do. After that, the SCP Service will take over and that worked for me.

Just wished it worked with the toolkit from the get go but oh well.

**Comment by luzair** [comment]
Whats the difference between the toolkit version and the old SCP 122 version, apart from supporting fake controllers.

**Comment by luzair** [comment]
@aking4125 You should try third party controllers, they can interchange between ps3 controller profile and x360 controller profile with just a press of a button. BUT they only last for a week. haha. I dun mind using them, if they were longer lasting and had rechargeable batteries.

**Comment by aking4125** [comment]
@luzair If you read my first post (Or any of them). I am using 3rd party Controllers. The "Fake" controllers. The Difference with the Toolkit and 1.2.2 is that the the Toolkit doesn't work for me via Bluetooth and the 1.2.2 one does as stated multiple times above. 

If you mean, real difference. Toolkit is easier to install, works with PS4 controllers, has profile settings on it's own. More options and is more sleeker.

**Comment by luzair** [comment]
@aking4125 Yes, I know, we're using fake controllers, me included, (i got deceived by seller that these controllers are legit, until I used toolkit). I know fake controllers work with bluetooth using 1.2.2 but not with toolkit. I mean other differences. In the toolkit, I noticed that we can assign battery status in the 4 leds instead of showing player 1. When I mean 3rd party controllers, i mean those that don't even look like ps3 controllers. Those that have turbo and / or auto fire functions sometimes.

**Comment by angelflames1337** [comment]
@aking4125 Holy shit my controller finally works via bluetooth. After installing, apparently I just need to press the back reset button using a needle, and it just seem to pair afterwards. Thanks mate!

**Comment by xendeus** [comment]
I hope PANHAI gamepad will work now. im still waiting for an update

**Comment by luzair** [comment]
Anybody knows how to have rumble support on fake controllers using SCP-DS-Driver-Package-1.2.2.175? Any help will be appreciated.

**Comment by aries-soft** [comment]
Download the moded ScpControl.dll from here, the dll was built for such devices.
Extract ScpControl.dll from the downloaded archive
Replace the ScpControl.dll in your bin folder with this.

http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller?pid=444231#pid444231

**Comment by luzair** [comment]
@aries-soft Can you confirm if the controller would work with vibration over bluetooth?

**Comment by aries-soft** [comment]
Works, but sometimes the vibration disappears

**Comment by luzair** [comment]
yup, tried it last nite, still no vibration. is there any additional drivers for the vibration?

**Comment by aries-soft** [comment]
Vibration via bluetooth only works with the new adapters (eg from 4.0 works there with the old 2.0)

**Comment by luzair** [comment]
ok. that gives me more variables for me to experiment on. will let you guys know, if i ever try it.

**Comment by luzair** [comment]
is there any app that tests the vibration on the controllers? it doesn't have the test vibration option in the 'game controllers' by windows.

**Comment by charlesmilette** [comment]
Any game that has a vibration feature may do the trick :)

[This link](http://www.getdare.com/bbs/showthread.php?t=146897) claims to say that you can test it with x360ce, but I haven't tried it.

**Comment by VarunBurde** [comment]
Hello,
@luzair @starg09 @aking4125 
Guys have you tried ScpServer_v1.5.5749.18036 .
Its working for me along with rumble.
https://github.com/nefarius/ScpToolkit/releases/tag/v1.5.5749.18036
try this link 
and thanks @nefarius for your great work.

**Comment by Fry1985** [comment]
@nefarius
The last release is from 10 Jan...
are u still working on the Problems?
When will fake Controllers probably be supported?
Im looking forward to that.
Great Work till now with this tool.
Keep it on. ;-)

@aries-soft
will the modded scpcontrol.dll work with SCP Toolkit or only with SCP DS3 Driver?
Does this modded dll make Fake controllers work? U said something about Rumble?
Thats not what this Thread is for.
http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller?pid=444231#pid444231

**Comment by aking4125** [comment]
@VarunBurde I have not. Will give it a shot when I'm free from IRL stuff. Will report back within' 24Hr

**Comment by nefarius** [comment]
@Fry1985 
I know.
Yes.
Don't know.
Great.
Thanks.
I try =]

**Comment by HoMiNeS** [comment]
I found a solution that works for me.

1- First install the new SCP Toolkit with bluetooth and the controller connected 
1.1 - if the remote is not detected press the "playstation / p3" button so it starts charging the remote
2 - When the monitor detects the controller and the bluetooth exit monitor
3 - open the 1.5.5749.18037 version and force install all the drivers.
4 - Now open the 1.5.5749 monitor and se if you can see bluetooth and Controller
5 - Click on playstation button while cable is on and see if it stay with only one light on (monitor will say charging)
6 - remove the cable (its on!!)

Rumble and wireless working, i have too fake controller uma with the p3 button and that one dont need nothing more than click the p3 button in the other that look exacly like ps3 controller you have to connect and disconnect the cable every time, but at least it work.

hope i help you guys. thanks a lot!

**Comment by pandapocalipse** [comment]
Hello guys, I was reading all the answers cause i'm also using a fake ps3 controller ( original one's cost more than 200$ in my country, damn ),and had the same problem with bluetooth connection, I don't mind not having rumble, but i really liked the configs on the SCPToolkit, especially the dead zone configuration, and would like to know if there's a way to use it on the SCPdriverpackage. I'll try @HoMiNeS solution

**Comment by parmeet2727** [comment]
First of all,i tried to connect my fake ds3 to my pc via motionin joy with no  luck
Then i tried to work around with scp toolkit, again with no luck
(it used to work with wire somehow).
Then i used the older SCP DRIVER V1.2.0.160+V.1.2.0.175 update and the Xinput wrapper dll file ,and VOILA it started working like charm(both with cable and usb) but BT had issues with vibration.
Last step was to connect an original DS3 and the connect the fake one.
Now everything works perfectly fine and smooth.
DLL link:http://forums.pcsx2.net/attachment.php?aid=54965
SCP OLD +UPDATE FILES:http://forums.pcsx2.net/attachment.php?aid=49455

**Comment by sarebots** [comment]
Bluetooth worked with my fake (apparently) ds3 with SCP DRIVER V1.2.0.160+V.1.2.0.175 update and the Xinput wrapper dll file. (Didn't work with SCP Toolkit)
Vibration does not work with bluetooth. I want to try what parmeet2727 said about connecting an original ds3, but i don't have one. I'm using a usb 2.0 dongle, so I guess I'll just manage without vibration when playing wirelessly.

**Comment by SAAF16** [comment]
i have 2 fake ds3, using the parmeet2727 method (SCP OLD +UPDATE FILES and DLL) i can get only 1 controller correctly connected, the second one is connected but it shows "bth 0000000000 none". is there any new solution to get fake controller work on bluetooth ?

**Comment by 7710101** [comment]
fake controller fixed   https://drive.google.com/file/d/0B02BQcVF2DX9ajc1NTdfRnRpNkU/view?usp=sharing

**Comment by 7710101** [comment]
ScpServer   fake controller vibration fix 
https://drive.google.com/file/d/0B02BQcVF2DX9ajc1NTdfRnRpNkU/view?usp=sharing

**Comment by 7710101** [comment]
read the text file

**Comment by Psycoguana** [comment]
After using it via Bluetooth for a while, every button I press is delayed. There are around 5'' between the time i press a key in the controller and when the game detects it. I tried this in several games, getting the same response in every one of them. It work ok with cable (not with an USB extension)

**Comment by cww1988** [comment]
I just used the latest version  of Scarlet crush xinput wrapper and the update, and copied Xinput_3 and 4 from x86 and x64 to the appropriate folders and replaced them.. Now my fake PS3 controller works with Black ops 2 and any game I need it to. It always froze up on nefarius's drivers. I don't know about bluetooth but it worked for a wired one.  nefarius had an awesome set up and is awesome for continuing the project. But until he has more time to add fake controllers this will work for me. Thanks for making the software nefarius. I love your installer and everything more than scarlet's though :).

**Comment by nihakue** [comment]
FWIW, I am experiencing the exact same symptoms as @starg09 on the same setup. Is there any further information I can provide that would be useful in tracking down the source of the problem? Thanks for all the hard work 👍

**Comment by eulercamposbarros** [comment]
I have the same setup described by @starg09 and I could make it work! I just uncommented some lines that @nefarius left on the source... and now all my fake gamepads works on bluetooth!

So I built the ScpControl.dll with the uncommented code. As @nefarius wrote on the source, this change may not work for all fake ds3 pads but since it worked for me, I wanna share with you guys... maybe it help someone else.

[Download the DLL here](https://goo.gl/UrVGdJ)

Thats the code I uncommented and solved my specific case:
File: ScpControl/Bluetooth/Ds3/BthDs3.cs
Source:
```
// TODO: this works for some but breaks others, so... dafuq >_<
if (IsFake)
{
	//_hidOutputReport[0] = 0xA2;
	//_hidOutputReport[3] = 0xFF;
	//_hidOutputReport[5] = 0x00;
}
```

To make it work, just copy this dll to your ScpToolkit folder (I recommed you make a copy of your original dll in case this change does not work for you). Remember, this dll is built for version **1.6.232.16004**

Hope it help someone and thx for your work @nefarius!

**Comment by nihakue** [comment]
@eulercamposbarros That solved the problem for me, thanks! Any clue why this solves the problem? How did you track it down?

**Comment by lovetheories** [comment]
Hello! After hours or reading and trial error I registered here to find some light. I hope someone could help me. Pleeeeaseeee >_<

I have a Gioteck VX2 BT controller. It is a 3rd party ps3 one with no dongle, so It should work out the box, but... after try the DS3 server (in all versions and configs possible) and then the more fancy toolkit... I have a BIG problem.

Controller never gets recognized with bluetooth and i mean NEVER. I have a compatible atheros one. Ok, no worries.
**But even don't work** in wired mode, because in devices keeps changing all the time from ps3 to gioteck (endessly...). This only happens when I install from toolkit. From DS3 server it doesnt do anything either. 

I tried beta o pre-release and in that, it only detects the controller 1 seconds when I plug or unplug the usb cable. After that, dissappears. 

I have no idea that what I'm doing wrong. Any of you have an idea? 
@nefarius I don't want to bother you, but if you have a look... 

Thanks in advance.

**Comment by auledoom1** [comment]
Uninstall last version, cleanup, install version 1.6.238, copy dll, restart windows... test everything ok with usb, unplugg ... try to connect ... nothing ... curse all hell for aprox 40 secs... tadammm 0.0!!!... my fake controller was detected and working... cry in joy... thanks @nefarius and thanks @eulercamposbarros for the patch!!

**Comment by tu0mas** [comment]
Got a fake one too. USB was working but not with bluetooth. Just used the ScpControll.dll, works like a charm now. Thank you!!!!!

**Comment by Psycoguana** [comment]
Can someone please give me a link to 1.6.232.16004 version? I looked in https://github.com/nefarius/ScpToolkit/releases but wasn't able to find it
