### ISSUE TITLE
keep getting bsod when connecting ps4 controller

### ISSUE THREAD

**Issue by kewlp** [nefarius/ScpToolkit#920]
I keep getting scpvbus.sys bsod when connecting.
tried clean wipe already and manual wipe (but i can't find it in services.msc).

how do i fix this and stop getting BSOD?

**Comment by Gnoce** [comment]
I have the same problem! Everything worked fine to this day. I tried everything but PC crash on BSOD as I switch on the DS4.
This is caused by the following module: scpvbus.sys
Bugcheck code: 0xC9 (0x7, 0xFFFFF803140C1B8C, 0xFFFF898D18722EA0, 0x0)
Error: DRIVER_VERIFIER_IOMANAGER_VIOLATION
file path: C: \ WINDOWS \ system32 \ drivers \ scpvbus.sys
product: Scp Virtual Bus Driver
company: Scarlet.Crush Productions
description: Scp Virtual Bus Driver
It's like Windows no longer recognizes the validity of this driver. Is there a solution or did they find a way to sell the xbox controllers?

**Comment by Gnoce** [comment]
Ok, I found a solution:

1. Use ScpToolkit Clean Wipe Utility - Reboot
2. Re-install driver
3. Open command prompt as administrator
4. run verifier
5. select Delete existing settings.
6. Reboot the computer.
Done ;)
