### ISSUE TITLE
False "fake controller" report

### ISSUE THREAD

**Issue by Nounours2627** [nefarius/ScpToolkit#922]
I've bought a new PS3 in a shop. I bought a seperate controller (to have two controllers) at the same moment in the same shop. 

I don't know which one is which one but the 2 controllers are CECHZC2E A1 and B1. Thet're not like my friend's controllers which are just ""CECHZC2E" nothing more. My friend's one is "Genuine" for SCP but my B1 is "fake" for SCP...

Does REAL shop sell fake controllers??? (and full price!) If not... SCP is probably considering the newest pad as fake.

**Comment by rkubes** [comment]
I also have this issue with CECHZC2U B1; This is a "DUALSHOCK 3" "SIXAXIS" controller. I bought it at Wal-Mart. SCP claims it's fake, but there is no issue using it. The only "weird" thing is when the controller disconnects from Bluetooth due to the timeout, SCP pops up an error. This does not happen if I disconnect the controller by holding the PS button - only if it times out from inactivity. With that said, the error has no adverse effect. I can reconnect without issue.

**Comment by rkubes** [comment]
I found the solution in #179. See the post from nefarius on Apr 18, 2016.

Quoted below for reference.

After you make this change, you need to restart the "SCP DSx Service" windows service (or restart Windows).

This will also supposedly fix any jitter that would occur when connected over USB. I haven't confirmed this yet.

> Your controller uses a Bluetooth chip from AzureWave Technologies Inc., did a bit of research and it looks like Sony also uses their chips in some VAIO notebook models so I guess we can assume the controller is genuine. Meanwhile you could try to add the line GenuineMacAddress = 08:A9:5A in ScpControl.ini below the section [Host Controller Interface] (on a "problematic" version ofc.) and see if behavior changes for you.
