### ISSUE TITLE
Vibration/Rumble doesn’t work on DS3 controller

### ISSUE THREAD

**Issue by punkdthrice** [nefarius/ScpToolkit#954]
I’m trying to get my DS3 controller to function properly on my PC. Originally I used the old Scarlett Crush Production drivers and vibration used to work. I did a reformat on my PC and it has never been the same.

Today I decided to install SCPToolKit for my Ps3 controller. All inputs and buttons work except for rumble/vibration. Disable rumble isn't checked in configuration nor is it disabled in game. Vibration works when controller is being used with my PS3 so the controller isn’t broken. Now it doesn’t work with XInput games. I haven’t tested with emulators.

How do I test rumble and get it to work properly? Should I run the Clean Wipe utility? I’m not sure what it does. Any help would be appreciated. Thanks in advance.

**Comment by SilentPrayeCG** [comment]
Clean Wipe uninstall all scp related drivers and services, so you can install them through driver install utility again.
You can try it. There is warning, about risks, but since i have this problem https://github.com/nefarius/ScpToolkit/issues/939 i forced to use Clean Wipe very often, and so far it works without problems (and without reboots requiring).

It does't uninstall scp files from installation folder, only from system.

**Comment by heltonteixeira** [comment]
Same issue here, tried different releases, did clean install a couple of times, tried to clean wipe, nothing made the force feedback/rumble work.

I'm using cable, and not the BT adapter, I don't know if it makes any difference.
